version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      DD_AGENT_HOST: datadog
      DD_ENV: "production"
      DD_SERVICE: "integrador-cat-api"
      DD_VERSION: "1.0.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    depends_on:
      - datadog

  datadog:
    image: "gcr.io/datadoghq/agent:latest"
    environment:
      - DD_API_KEY=${{ secrets.DATADOG_API_KEY }}
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_ENV=production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
